- src/main/java/GDG/whatssue/controller/OfficialAbsenceController.java
- src/main/java/GDG/whatssue/service/OfficialAbsenceService.java
- src/main/resources/application.yml
> Feat: 공결 관련 api 에러 수정

- src/main/java/GDG/whatssue/controller/ClubSettingController.java
- src/main/java/GDG/whatssue/controller/OfficialAbsenceController.java
- src/main/java/GDG/whatssue/dto/ClubSetting/SettingClubDto.java
- src/main/java/GDG/whatssue/entity/Club.java
- src/main/java/GDG/whatssue/repository/ClubRepository.java
- src/main/java/GDG/whatssue/service/ClubSettingService.java
모임 생성, 수정, 삭제 api 구현 및 공결 관련 api summary 추가
> Feat: 모임 생성, 수정, 삭제 구현

- src/main/java/GDG/whatssue/domain/member/entity/ClubMember.java
- src/main/java/GDG/whatssue/domain/member/repository/ClubJoinRequestRepository.java
- src/main/java/GDG/whatssue/domain/member/repository/ClubMemberRepository.java
- src/main/java/GDG/whatssue/domain/memberJoin/controller/MemberJoinController.java
- src/main/java/GDG/whatssue/domain/memberJoin/dto/ClubJoinRequestGetDto.java
- src/main/java/GDG/whatssue/domain/memberJoin/repository/MemberJoinRepository.java
- src/main/java/GDG/whatssue/domain/memberJoin/service/MemberJoinService.java
- src/main/java/GDG/whatssue/domain/officialabsence/entity/OfficialAbsenceRequest.java
Feat: clubJoinRequest 수락, 거절, 멤버 삭제 구현
> Feat: clubJoinRequest 수락, 거절, 멤버 삭제 구현

- src/main/java/GDG/whatssue/domain/officialabsence/controller/OfficialAbsenceController.java
- src/main/java/GDG/whatssue/domain/officialabsence/entity/OfficialAbsenceRequest.java
- src/main/java/GDG/whatssue/domain/officialabsence/repository/OfficialAbsenceRequestRepository.java
- src/main/java/GDG/whatssue/domain/officialabsence/service/OfficialAbsenceService.java
> Feat: 공결 api 대기 여부 필터링 수정 적용

- src/main/java/GDG/whatssue/domain/officialabsence/controller/OfficialAbsenceController.java
- src/main/java/GDG/whatssue/domain/officialabsence/repository/OfficialAbsenceRequestRepository.java
- src/main/java/GDG/whatssue/domain/officialabsence/service/OfficialAbsenceService.java
> Feat: 공결 신청 취소 api

- src/main/java/GDG/whatssue/domain/club/controller/ClubController.java
- src/main/java/GDG/whatssue/domain/club/controller/ClubJoinController.java
- src/main/java/GDG/whatssue/domain/club/repository/ClubRepository.java
- src/main/java/GDG/whatssue/domain/club/service/ClubService.java
- src/main/java/GDG/whatssue/domain/club/service/impl/ClubServiceImpl.java
- src/main/java/GDG/whatssue/domain/member/entity/ClubMember.java
- src/main/java/GDG/whatssue/domain/member/service/ClubMemberService.java
- src/main/java/GDG/whatssue/domain/member/service/impl/ClubMemberServiceImpl.java
- src/main/java/GDG/whatssue/domain/schedule/controller/ScheduleController.java
- src/main/java/GDG/whatssue/global/common/ClubManager.java
- src/main/java/GDG/whatssue/global/config/WebConfig.java
- src/main/java/GDG/whatssue/global/config/WebSecurityConfig.java
- src/main/java/GDG/whatssue/global/error/GlobalExceptionHandler.java
- src/main/java/GDG/whatssue/global/interceptor/ClubCheckInterceptor.java
/api/clubs/{clubId} 의 url에 대하여 다음 세가지 체크
1. 존재하는 클럽인가?
2. 로그인 유저가 해당 클럽의 멤버인가?
3. 로그인 유저가 해당 클럽의 관리자인가? (@ClubManager 애노테이션이 붙은 메서드에 한하여)
> 클럽 관련 api 권한 체크 인터셉터 구현

- src/main/java/GDG/whatssue/domain/officialabsence/entity/OfficialAbsenceRequest.java
- src/main/java/GDG/whatssue/domain/officialabsence/entity/OfficialAbsenceRequestType.java
- src/main/java/GDG/whatssue/domain/officialabsence/repository/OfficialAbsenceRequestRepository.java
- src/main/java/GDG/whatssue/domain/officialabsence/service/OfficialAbsenceService.java
NOT_CHECKED, ACCEPTED, DENIED로 구분되는 공결 신청 table Enum 컬럼 추가
> feat: 공결 신청 table Enum 컬럼 추가

- src/main/java/GDG/whatssue/domain/schedule/dto/GetScheduleDetailResponse.java
- 일정 상세 조회 시 장소, 등록 시간, 등록 멤버 반환
- 일정 출석 여부 -> 일정 출석 상태(ENUM) AttendanceStatus(BEFORE, ONGOING, COMPLETE)
> Feat: 일정 api 수정

- src/main/java/GDG/whatssue/domain/post/controller/PostController.java
- src/main/java/GDG/whatssue/domain/post/dto/UpdatePostRequest.java
- src/main/java/GDG/whatssue/domain/post/service/PostService.java
Feat: PostController 기본 로직 구현
PostController 권한 체크 분기점 구현
> Feat: PostController 기본 로직 구현

- src/main/java/GDG/whatssue/domain/officialabsence/exception/OfficialAbsenceErrorCode.java
- src/main/java/GDG/whatssue/domain/officialabsence/service/OfficialAbsenceService.java
Refactor: 공결 코드 에러 반환 리팩토링
에러 코드 명세 사항대로 반환하도록 수정.
> Refactor: 공결 코드 에러 반환 리팩토링

- src/main/java/GDG/whatssue/domain/post/controller/PostController.java
- src/main/java/GDG/whatssue/domain/post/entity/Post.java
- src/main/java/GDG/whatssue/domain/post/exception/PostErrorCode.java
- src/main/java/GDG/whatssue/domain/post/service/PostService.java
Feat: PostController API 구현
생성, 수정, 삭제 구현
> Feat: PostController API 구현

- src/main/java/GDG/whatssue/domain/club/entity/Club.java
- src/main/java/GDG/whatssue/domain/club/exception/ClubErrorCode.java
- src/main/java/GDG/whatssue/domain/club/service/ClubService.java
- src/main/java/GDG/whatssue/domain/clubjoinrequest/service/ClubJoinService.java
- src/main/java/GDG/whatssue/domain/schedule/controller/ScheduleController.java
- src/main/java/GDG/whatssue/domain/schedule/entity/Schedule.java
- src/main/java/GDG/whatssue/domain/schedule/repository/ScheduleRepository.java
- src/main/java/GDG/whatssue/domain/schedule/service/ScheduleService.java
가입 신청 받지 않는 클럽일 시에 예외처리
EX3205
> 일정 조회 및 가입 신청 검증 로직 추가

- src/main/java/GDG/whatssue/domain/post/controller/PostController.java
- src/main/java/GDG/whatssue/domain/post/service/PostService.java
Fix: isLikedCheck 멤버 조회 오류 수정
멤버 검색 조건 userId -> memberId로 수정
> Fix: isLikedCheck 멤버 조회 오류 수정

- src/main/java/GDG/whatssue/domain/post/controller/PostController.java
- src/main/java/GDG/whatssue/domain/post/service/PostService.java
- src/main/java/GDG/whatssue/domain/schedule/controller/ScheduleController.java
Fix: postAPI @LoginMember 어노테이션 제거
> Fix: postAPI @LoginMember 어노테이션 제거

- src/main/java/GDG/whatssue/domain/post/controller/PostController.java
- src/main/java/GDG/whatssue/domain/post/dto/GetPostResponse.java
- src/main/java/GDG/whatssue/domain/post/repository/PostQueryRepository.java
- src/main/java/GDG/whatssue/domain/post/service/PostService.java
Feat: postAPI GET메서드 개선
searchPosts검색 조건에 category 필수 선택하도록 수정
모든 post GET메서드 응답값에 createdAt, 댓글수를 포함하도록 수정
> Feat: postAPI GET메서드 개선

- src/main/java/GDG/whatssue/domain/post/controller/PostController.java
- src/main/java/GDG/whatssue/domain/post/repository/PostRepository.java
- src/main/java/GDG/whatssue/domain/post/service/PostService.java
Feat: 내가 쓴 글, 내가 좋아요 한 글 조회 API 구현
> Feat: 내가 쓴 글, 내가 좋아요 한 글 조회 API 구현

- src/main/java/GDG/whatssue/domain/schedule/entity/AttendanceStatus.java
- src/main/java/GDG/whatssue/domain/schedule/entity/Schedule.java
- src/test/java/GDG/whatssue/domain/schedule/entity/ScheduleTest.java
- 일정 출석 시작(성공, 실패)
- 일정 출석 종료(성공, 실패)
- 일정 수정
> 일정 biz 로직 단위테스트 진행

- src/main/java/GDG/whatssue/global/error/GlobalExceptionHandler.java
Fix: allExHandle e.getMessage log 출력하도록 수정
> Fix: allExHandle e.getMessage log 출력하도록 수정

- src/main/java/GDG/whatssue/domain/officialabsence/controller/OfficialAbsenceController.java
- src/main/java/GDG/whatssue/domain/officialabsence/dto/OfficialAbsenceGetRequestDto.java
- src/main/java/GDG/whatssue/domain/officialabsence/entity/OfficialAbsenceRequest.java
- src/main/java/GDG/whatssue/domain/officialabsence/exception/OfficialAbsenceErrorCode.java
- src/main/java/GDG/whatssue/domain/officialabsence/repository/OfficialAbsenceRequestRepository.java
- src/main/java/GDG/whatssue/domain/officialabsence/service/OfficialAbsenceService.java
Feat: 공결 반환 API 페이징 처리
- 공결 목록을 반환하는 API 페이징 처리
- api 경로 변경
- 공결 반환시 clubId 검색 조건 추가
- 일부 api 본인 확인 조건 추가
> Feat: 공결 반환 API 페이징 처리

- src/main/java/GDG/whatssue/domain/post/controller/PostController.java
- src/main/java/GDG/whatssue/domain/post/dto/UpdatePostRequest.java
- src/main/java/GDG/whatssue/domain/post/entity/Post.java
- src/main/java/GDG/whatssue/domain/post/repository/PostRepository.java
- src/main/java/GDG/whatssue/domain/post/service/PostService.java
Fix : PostAPI 누락, 에러 사항 수정
post의 CRUD url 통일
deletePostImages메서드 upload_file값을 삭제하지 않던 사항 수정
updatePost메서드의 @Transactional 어노테이션 누락 수정
updatePost메서드의 권한확인 예외처리가 올바르지 않게 작동하던 사항 수정
내가 쓴 글, 내가 좋아요한 글 반환 API 카테고리 조건 삭제
> Fix : PostAPI 누락, 에러 사항 수정

- src/main/java/GDG/whatssue/domain/post/service/PostService.java
Fix : 게시글 조회시 삭제된 댓글 count 제외하도록 수정
게시글 조회시 삭제된 댓글 count 제외하도록 수정
대댓글이 있는 댓글은 count 포함
> Fix : 게시글 조회시 삭제된 댓글 count 제외하도록 수정

- .github/PULL_REQUEST_TEMPLATE.md
- src/main/java/GDG/whatssue/domain/file/entity/UploadFile.java
- src/main/java/GDG/whatssue/domain/member/controller/ClubMemberController.java
- src/main/java/GDG/whatssue/domain/member/dto/CreateMemberProfileRequest.java
- src/main/java/GDG/whatssue/domain/member/entity/ClubMember.java
- src/main/java/GDG/whatssue/domain/member/exception/ClubMemberErrorCode.java
- src/main/java/GDG/whatssue/domain/member/service/ClubMemberService.java
- src/main/java/GDG/whatssue/global/common/annotation/SkipFirstVisitCheck.java
- src/main/java/GDG/whatssue/global/interceptor/ClubCheckInterceptor.java
- src/main/resources/application.yml
멤버 프로필 등록 api 완성~
1. @ModelAttrubute(Form-Data) 이용
2. @SkipFirstVisitCheck annotation 추가 ; intercepter에서  첫방문 여부에 걸리지 않게 하기 위함
3. Pull Request 템플릿 추가
> 프로필 조회 API 

- src/main/java/GDG/whatssue/domain/member/controller/ClubMemberController.java
- src/main/java/GDG/whatssue/domain/member/entity/ClubMember.java
- src/main/java/GDG/whatssue/domain/member/service/ClubMemberService.java
> fix : 프로필 수정 api

- src/main/java/GDG/whatssue/domain/post/controller/PostController.java
- src/main/java/GDG/whatssue/domain/post/dto/UpdatePostRequest.java
- src/main/java/GDG/whatssue/domain/post/entity/Post.java
- src/main/java/GDG/whatssue/domain/post/exception/PostErrorCode.java
- src/main/java/GDG/whatssue/domain/post/service/PostService.java
Feat : 게시글 업데이트시 기존 이미지 유지, 삭제, 사진 순서 지정 기능 추가
> Feat : 게시글 업데이트시 기존 이미지 유지, 삭제, 사진 순서 지정 기능 추가

- src/main/java/GDG/whatssue/domain/officialabsence/dto/OfficialAbsenceGetRequestDto.java
- src/main/java/GDG/whatssue/domain/officialabsence/service/OfficialAbsenceService.java
Feat: 공결 신청 조회시 추가적인 정보를 반환하는 로직 추가
공결 신청 조회 시 일정 이름, 날짜, 수락/거절 날짜 반환하기 추가.
> Feat: 공결 신청 조회시 추가적인 정보를 반환하는 로직 추가

- src/main/java/GDG/whatssue/domain/officialabsence/exception/OfficialAbsenceErrorCode.java
- src/main/java/GDG/whatssue/domain/officialabsence/service/OfficialAbsenceService.java
Feat: '출석이 진행된 일정'에 대한 공결 신청 생성, 수락/거절이 불가능하도록 수정
일정에 대한 attendance_status이 BEFORE인 경우에만
공결 신청 생성, 공결 신청 수락(MANAGER), 공결 신청 거절(MANAGER)이 가능하도록 수정
> Feat: '출석이 진행된 일정'에 대한 공결 신청 생성, 수락/거절이 불가능하도록 수정

- src/main/java/GDG/whatssue/domain/club/controller/ClubController.java
- src/main/java/GDG/whatssue/domain/clubjoinrequest/controller/ClubJoinController.java
- src/main/java/GDG/whatssue/domain/file/entity/ClubProfileImage.java
- src/main/java/GDG/whatssue/domain/file/entity/MemberProfileImage.java
- src/main/java/GDG/whatssue/domain/file/entity/PostImage.java
- src/main/java/GDG/whatssue/domain/file/entity/UploadFile.java
- src/main/java/GDG/whatssue/domain/member/repository/ClubMemberRepository.java
- src/main/java/GDG/whatssue/domain/schedule/controller/ScheduleController.java
- src/main/java/GDG/whatssue/domain/schedule/entity/Schedule.java
- src/main/java/GDG/whatssue/domain/schedule/repository/ScheduleRepository.java
- src/main/java/GDG/whatssue/domain/schedule/service/ScheduleService.java
> 이미지 테이블 상속전략 변경 & 일정 존재 일자조회 api
